name: vies
description: This dart lib is basically calling web service provided by VIES for check VAT validity
version: 1.0.1
homepage: https://www.restomax.com
repository: https://github.com/raphrmx/vies
issue_tracker: https://github.com/raphrmx/vies/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html_unescape: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  lint: ^1.8.2
  test: ^1.20.1
