name: vies
description: This dart lib is basically calling web service provided by VIES for check VAT validity
version: 1.1.0
homepage: https://www.comapps.be
repository: https://github.com/raphrmx/vies
issue_tracker: https://github.com/raphrmx/vies/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  html_unescape: ^2.0.0
  http: ^1.1.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.6
